# Generated by Django 5.2 on 2025-05-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_roomimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomimages",
            name="images",
            field=models.ImageField(upload_to="hotels"),
        ),
    ]
